spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school_db
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect