site.url: https://8080-abdulazizkh-signuplogin-3yqxbzikqjv.ws-eu63.gitpod.io/api/auth/confirm?token=

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-28.railway.app:7851/railway
    username: postgres
    password: Wr2hmlekopfTHhvswnxf
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  mail:
    # host: smpt.yandex.com
    # port: 465
    # username: abdulazizkhan.k.n.b@yandex.com
    # password: itechdott
    host: smtp.gmail.com
    port: 587
    username: itechdott@gmail.com
    password: aejvmrufrojqddkz

    properties:
      mail:
        smtp:
          starttls:
            enabled: true
            required: true
          auth: true

          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000