
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_jpa_db
    username: security_user
    password: secret321
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true